version: 2
before:
  hooks:
    - ./scripts/completions.sh
    - ./scripts/manpages.sh

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 5
      - 6
      - 7
    gomips:
      - softfloat
    ignore:
      - goos: windows
        goarch: arm
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X github.com/prometheus/common/version.Version={{.Version}} -X github.com/prometheus/common/version.BuildDate={{.Date}} -X github.com/prometheus/common/version.Branch={{.Branch}} -X github.com/prometheus/common/version.BuildUser=goreleaser"

changelog:
  disable: true

archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*

sboms:
  - artifacts: archive
    documents:
      - "${artifact}.spdx.json"

brews:
  - repository:
      owner: nginx
      name: homebrew-tap
      token: "{{ .Env.NGINX_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/nginx/nginx-prometheus-exporter
    description: NGINX Prometheus Exporter for NGINX and NGINX Plus
    license: Apache-2.0
    commit_author:
      name: nginx-bot
      email: integrations@nginx.com
    extra_install: |-
      bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
      zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
      man1.install "manpages/nginx-prometheus-exporter.1.gz"

signs:
  - cmd: cosign
    artifacts: checksum
    output: true
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"
      - "--yes"

announce:
  slack:
    enabled: true
    channel: "#announcements"
    message_template: "NGINX Prometheus Exporter {{ .Tag }} is out! Check it out: {{ .ReleaseURL }}"

milestones:
  - close: true

snapcrafts:
  - name_template: "{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    title: NGINX Prometheus Exporter
    summary: NGINX Prometheus Exporter for NGINX and NGINX Plus
    description: |
      NGINX Prometheus exporter fetches the metrics from NGINX or NGINX Plus,
      converts the metrics into appropriate Prometheus metrics types and finally exposes
      them via an HTTP server to be collected by Prometheus.
    grade: stable
    confinement: strict
    publish: true
    license: "Apache-2.0"
    apps:
      nginx-prometheus-exporter:
        command: nginx-prometheus-exporter
        plugs: ["network", "network-bind"]
        completer: completions/nginx-prometheus-exporter.bash
    disable: "{{ if .IsSnapshot }}true{{ end }}"

nix:
  - name: nginx-prometheus-exporter
    repository:
      owner: nginx
      name: nur
      token: "{{ .Env.NGINX_GITHUB_TOKEN }}"
    homepage: https://github.com/nginx/nginx-prometheus-exporter
    description: NGINX Prometheus Exporter for NGINX and NGINX Plus
    license: asl20
    commit_author:
      name: nginx-bot
      email: integrations@nginx.com
    extra_install: |-
      installManPage ./manpages/nginx-prometheus-exporter.1.gz
      installShellCompletion ./completions/*

winget:
  - name: nginx-prometheus-exporter
    publisher: nginx
    license: Apache-2.0
    homepage: https://github.com/nginx/nginx-prometheus-exporter
    short_description: NGINX Prometheus Exporter for NGINX and NGINX Plus
    repository:
      owner: nginx
      name: winget-pkgs
      token: "{{ .Env.NGINX_GITHUB_TOKEN }}"
      branch: "nginx-prometheus-exporter-{{.Version}}"
      pull_request:
        enabled: true
        draft: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

scoops:
  - repository:
      owner: nginx
      name: scoop-bucket
      token: "{{ .Env.NGINX_GITHUB_TOKEN }}"
    directory: bucket
    homepage: https://github.com/nginx/nginx-prometheus-exporter
    description: NGINX Prometheus Exporter for NGINX and NGINX Plus
    license: Apache-2.0
    commit_author:
      name: nginx-bot
      email: integrations@nginx.com
